version: "3.9"

networks:
  edge:
    name: edge
    driver: bridge

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE: ${VITE_API_BASE:-https://api.3xprep.com}
    image: stride-frontend:latest
    environment:
      NODE_ENV: production
    restart: unless-stopped
    ports:
      - "8085:80"   # for direct testing via http://SERVER_IP:8085
    networks:
      - edge

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}   # <-- IMPORTANT: exact name
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - edge
