version: "3.9"
services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE: ${VITE_API_BASE:-https://api.3xprep.com}
    image: stride-frontend:latest
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
