version: "3.9"

networks:
  edge:
    name: edge
    driver: bridge

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE: ${VITE_API_BASE:-https://api.3xprep.com}
    image: stride-frontend:latest
    environment:
      NODE_ENV: production
    restart: unless-stopped
    # ❌ No public ports; cloudflared will reach this by service name
    networks:
      - edge

  cloudflared:
  image: cloudflare/cloudflared:latest
  command: ["tunnel", "--config", "/etc/cloudflared/config.yml", "run"]
  environment:
    - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  depends_on:
    - frontend
  volumes:
    - ./ops/cloudflared:/etc/cloudflared:ro   # directory contains config.yml
  restart: unless-stopped
  networks:
    - edge
