version: "3.9"

networks:
  edge:
    name: edge
    driver: bridge

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE: ${VITE_API_BASE:-https://api.3xprep.com}
    image: stride-frontend:latest
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - edge

  cloudflared:
    image: cloudflare/cloudflared:latest
    # Force cloudflared to read your local config file
    command: >-
      tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}   # must exist in .env (the long token)
    depends_on:
      - frontend
    volumes:
      - ./etc/cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    restart: unless-stopped
    networks:
      - edge
